[package]
name = "lambda-terraform"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
lambda_runtime = "^0.4.1"
serde = "^1.0"
serde_json = "^1.0"
tokio = "^1.15"
base64 = "^0.13"

[profile.release]
opt-level = 3
